### PR TITLE
feat: pass manager kwargs from namespace

### PR DESCRIPTION
**Pull request by devamin**
# WHY
I need to pass `ignore_queue` from namespace emit call. 
# WHAT 
Pass kwargs from namespace emit to server emit

### CODE REVIEW

**Comment by miguelgrinberg** [comment]
Thanks, this looks good in principle, but passing `kwargs` is not a good solution, as it makes it much harder to properly document these calls. So I would like to request two things:

1. Add any missing function arguments explicitly
2. Update the docstrings accordingly

Do you think you can make these changes? Thanks!

**Comment by devamin** [comment]
You welcome, thanks for you for creating this library. 
Yes I can handle these requirements.

**Comment by devamin** [comment]
@miguelgrinberg please let me know if all good, or there is something that I need to change/add.

**Comment by miguelgrinberg** [comment]
Thanks. There were a few missing things in this PR such as the same support for `ignore_queue` in `send()` and `call()`, and also the tests needed some updates to cope with these changes. I have committed a complete fix now.

**Pull request closed without merging**
