### PR TITLE
Kafka multiple brokerlist feature

### PR DESCRIPTION
**Pull request by sparkingdark**
Multiple kafka server usage for python-scoketio.

### CODE REVIEW

**Comment by miguelgrinberg** [comment]
The change looks good, but before I merge it I need you to fix the issues reported by the linter. Thanks!

**Comment by sparkingdark** [comment]
Okay

**Comment by sparkingdark** [comment]
@miguelgrinberg can you check now? in my local system still I got this warning 
```
src/socketio/kafka_manager.py:42:80: E501 line too long (80 > 79 characters)
src/socketio/kafka_manager.py:51:80: E501 line too long (82 > 79 characters)
```

**Comment by miguelgrinberg** [comment]
@sparkingdark why didn't you fix those warnings? I won't merge this until it passes all validation checks.

**Comment by sparkingdark** [comment]
I ran black for formatting,after I am getting the warning , should I need
fix that warning manually or flake8 has some automatic fix for this kind of
warning?

Tomorrow morning I will look into it.

**Comment by miguelgrinberg** [comment]
Don't worry about it, I just merged this myself. You were making this way more complicating that it needed to be. There were some minor style problems in the code that I hoped you would address by hand. While I have nothing against black, that hides the actual change in a lot of irrelevant formatting changes, so I removed the black fixes you added, and then manually fixed the couple of issues flagged by flake8. Thanks!

**Comment by miguelgrinberg** [comment]
@sparkingdark The style guide is [pep8](https://www.python.org/dev/peps/pep-0008/). But this is really common sense more than anything. If flake8 complains that a line is too long, just break it in two, and so on.

**Comment by sparkingdark** [comment]
Got it 👍

**Pull request closed without merging**
