### PR TITLE
really from python<=3.7 support

### PR DESCRIPTION
**Pull request by kloczek**
Filter all module code over `pyupgrade --py36`.

### CODE REVIEW

**Comment by miguelgrinberg** [comment]
Thanks, but at this time I'm not going to merge it. From the looks of it you just have used a tool to make these changes, and have not done any testing. Some of the changes are safe, but some I would need to test, but I do not have time to do that now.

When I can allocate some time to properly test I will use pyupgrade myself.

**Comment by kloczek** [comment]
> Thanks, but at this time I'm not going to merge it. From the looks of it you just have used a tool to make these changes, and have not done any testing. Some of the changes are safe, but some I would need to test, but I do not have time to do that now.

That is not true.
On building rpm I'm execution pytest ant passed without any issues with warnings printed without this commit.
<details>
<summary>Here is pytest output taken from build log of mu build automation:</summary>

```console
+ PYTHONPATH=/home/tkloczko/rpmbuild/BUILDROOT/python-socketio-5.11.1-2.fc35.x86_64/usr/lib64/python3.8/site-packages:/home/tkloczko/rpmbuild/BUILDROOT/python-socketio-5.11.1-2.fc35.x86_64/usr/lib/python3.8/site-packages
+ /usr/bin/pytest -ra -m 'not network'
============================= test session starts ==============================
platform linux -- Python 3.8.18, pytest-8.0.0, pluggy-1.3.0
rootdir: /home/tkloczko/rpmbuild/BUILD/python-socketio-5.11.1
collected 577 items

tests/async/test_admin.py ..........                                     [  1%]
tests/async/test_client.py ............................................. [  9%]
...........................                                              [ 14%]
tests/async/test_manager.py ..............................               [ 19%]
tests/async/test_namespace.py .....................                      [ 23%]
tests/async/test_pubsub_manager.py ..................................    [ 28%]
tests/async/test_server.py ............................................. [ 36%]
..............................                                           [ 41%]
tests/async/test_simple_client.py ................                       [ 44%]
tests/common/test_admin.py .........                                     [ 46%]
tests/common/test_client.py ............................................ [ 53%]
..........................................                               [ 61%]
tests/common/test_manager.py ...............................             [ 66%]
tests/common/test_middleware.py ...                                      [ 67%]
tests/common/test_msgpack_packet.py ....                                 [ 67%]
tests/common/test_namespace.py ..................                        [ 70%]
tests/common/test_packet.py ......................................       [ 77%]
tests/common/test_pubsub_manager.py .................................... [ 83%]
                                                                         [ 83%]
tests/common/test_server.py ............................................ [ 91%]
..................................                                       [ 97%]
tests/common/test_simple_client.py ................                      [100%]

=============================== warnings summary ===============================
tests/async/test_client.py::TestAsyncClient::test_send
tests/async/test_client.py::TestAsyncClient::test_send_packet_default_binary
  /usr/lib64/python3.8/unittest/mock.py:2030: RuntimeWarning: coroutine 'Event.wait' was never awaited
    setattr(_type, entry, MagicProxy(entry, self))
  Enable tracemalloc to get traceback where the object was allocated.
  See https://docs.pytest.org/en/stable/how-to/capture-warnings.html#resource-warnings for more info.

tests/async/test_manager.py::TestAsyncManager::test_close_invalid_room
  /home/tkloczko/rpmbuild/BUILD/python-socketio-5.11.1/tests/async/test_manager.py:193: RuntimeWarning: coroutine 'AsyncManager.close_room' was never awaited
    self.bm.close_room('bar', '/foo')
  Enable tracemalloc to get traceback where the object was allocated.
  See https://docs.pytest.org/en/stable/how-to/capture-warnings.html#resource-warnings for more info.

tests/async/test_manager.py::TestAsyncManager::test_disconnect_all
  /usr/lib64/python3.8/unittest/mock.py:2076: RuntimeWarning: coroutine 'TestAsyncClient.test_wait_reconnect_successful.<locals>.fake_wait' was never awaited
    self.name = name
  Enable tracemalloc to get traceback where the object was allocated.
  See https://docs.pytest.org/en/stable/how-to/capture-warnings.html#resource-warnings for more info.

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
================= 577 passed, 4 warnings in 130.33s (0:02:10) ==================
```
</details>

**Comment by kloczek** [comment]
Submitted patch it pure pyugrade result.

**Comment by kloczek** [comment]
And if something has been incorrectly filtered by pypgrade please report that to https://github.com/asottile/pyupgrade/

**Pull request closed without merging**
