### PR TITLE
Integration with Kafka #507

### PR DESCRIPTION
**Pull request by VincentM**
Hi, 

After reading this issue : https://github.com/miguelgrinberg/Flask-SocketIO/issues/507, I created a custom backend to use python-socketio with Kafka.

Currently it's worked fine with kafka-python. I plan to add the capability to choose between confluent-kafka-python or python-kafka (another PR will be coming soon if this one is correct).

I test it on a kubernetes cluster with dozen backends.

Please, tell me if any corrections are necessary. I will be happy to improve this feature.

PS : Simultaneously, I made a PR on Flask-SocketIO.

### CODE REVIEW

**Comment by VincentM** [comment]
Hi @nahidalam,

First at all, please, tell me if something is not clear. English is not my mother tongue :-) (I'm French).

Here is the use case for others messages queues (as Redis) : http://python-socketio.readthedocs.io/en/latest/#using-a-message-queue

I illustrate the behavior in the attached picture :

capture d ecran 2018-06-09 00 54 02

First we have two clients (client 1 and client 2) connected to the same instance of our server (a flask application by example). Theses clients can share messages because they are connected to the same Socket.io server.

Then, due to performance issues, we add another instance of our application (horizontal scaling) and another client connects to the new instance. 

Because they are connected on two differents Socket.io servers, 'Client 1' and 'Client 2' can not share messages with 'Client 3'. 

Here appears the message queue. Each Socket.io server is connected to the message queue.

Ex: 'Client 1' sends a message. The Socket.io server of the 'Instance 1' produces a message on a kafka topic. The Socket.io server of the 'Instance 2' has subscribed to the kafka topic, consumes the message and send it to the 'Client 3'.

All this behaviour is transparent, all you need is configure your Socket.IO instance to use kafka (see below).


Example of codes (requirement : python-kafka must be installed): 

```python
    app = Flask(__name__)
	socketio = SocketIO(async_mode='eventlet')
    socketio.init_app(app, message_queue='kafka://localhost:9092') # Assume that Kafka is running on localhost (port 9092)

    ... # Just use socketio.on, send and emit as if you're not using message queue, this is transparent.
```

Of course, to use Kafka with Flask-SocketIO and python-socketio, you have to wait that my PR are integrated. (You could use my temporarly repos for testing, but i will not maintain them anymore, so please, consider to use miguel's repo for production).

I hope I helped you. I could create a git with a functional Flask application next week (from friday), tell me if is it necessary ?

**Comment by mohithg** [comment]
This should be merged along with #700. Please merge this, as it is the really useful feature.

**Comment by miguelgrinberg** [comment]
@mohithg I intend to merge it, but I haven't had time to test and review this myself, and also update the documentation, which the PR owner did not do. Consider that it will be on me to maintain this code going forward, it's not just pushing a button to merge.

You can still use this code if you want, just install the PR branch in your virtual environment.

**Comment by akshaychand** [comment]
@miguelgrinberg - Any update on whether this will be merged in the near future. I apologize if it has already been.

**Comment by akshaychand** [comment]
> @miguelgrinberg - Any update on whether this will be merged in the near future. I apologize if it has already been.

Thank you, thank you!!

**Pull request merged**
