### PR TITLE
Migrate to aioredis 2.0

### PR DESCRIPTION
**Pull request by sam-mosleh**
This PR fixes issue #771

### CODE REVIEW

**Comment by miguelgrinberg** [comment]
You have changed a lot of other things besides upgrade aioredis. Why?

**Comment by miguelgrinberg** [comment]
Thanks. After looking at your PR in more detail I do see that these changes are justified. I have now merged your PR with some changes which made the code closer to the regular Redis client manager. Thank you!

**Comment by miguelgrinberg** [comment]
@sam-mosleh To me the most important thing is to have parity between the two Redis implementations. I did not really look at every minor change you've made, I just replaced your solution with the existing one in the sync redis. If you have any suggestions to improve the redis implementation you are welcome to submit a PR targeting both, which are now almost identical.

**Comment by miguelgrinberg** [comment]
@cnicodeme I was hoping to look into https://github.com/miguelgrinberg/python-socketio/pull/806 more in detail before releasing, but haven't had time to look into that yet.

**Comment by miguelgrinberg** [comment]
@cnicodeme 5.5.0 is now out with this change.

**Comment by cnicodeme** [comment]
Awesome, thank you @miguelgrinberg !

**Comment by cnicodeme** [comment]
I just updated to 5.5.0 and noticed a previous bug that is still present (Also mentioned in #505). 

The problem is indeed a backward incompatible update from Sanic : They moved the HTTPResponse and WebSocketProtocol to another path, making the import to fail.

I've previously brought a suggestion at: https://github.com/miguelgrinberg/python-engineio/issues/251

**Comment by miguelgrinberg** [comment]
@cnicodeme I consider Sanic support much lower priority, did not plan to have it fixed in this release. In fact I've been thinking about dropping Sanic from the support list, because they often break things, it's a lot of effort to keep up with them. The Sanic implementation is already hacky because they make it extremely difficult to support a route that is both HTTP and WebSocket.

**Comment by cnicodeme** [comment]
Yeah I can understand the issue.

I'm all ok with dropping the support, but in that case, would there be - if not already - a way to implement a custom integrations?

I'm mentioning this because in the current structure, it's not possible to extract the Sanic integration and use `async_mode` when creating the AsyncServer, because the mode 'sanic' is hard written in the `AsyncServer` class at https://github.com/miguelgrinberg/python-engineio/blob/main/src/engineio/asyncio_server.py#L76

**Pull request closed without merging**
