### PR TITLE
Handle RabbitMQ disconnects

### PR DESCRIPTION
**Pull request by xarg**
⚠️  Not ready to merge, please read below

Relates to #100

### Features:

- Made exchange durable - the change is explained here: https://github.com/celery/kombu/issues/763
- Always retry sending/consuming after connection errors.

### Unresolved issues:

- [x] Since in production environment the exchange and the queues are already declared as durable/non-durable - how can we redeclare them as durable? Is there a way to migrate them? If I just change the durability i get this error: `PreconditionFailed: Exchange.declare: (406) PRECONDITION_FAILED - inequivalent arg 'durable' for exchange`
- [ ] How do I test this?

### CODE REVIEW

**Comment by miguelgrinberg** [comment]
The issue you referenced contains the following statement:

> So if you have a non-durable Exchange with some durable Queues attached to it then after restart it's just hangs there zombie like, not able to accept any new consumers

Have you considered making the queues non-durable instead? Doesn't that also solve the issue, without creating durable resources that will then have to be cleaned up by hand if you are just running a quick test?

**Comment by xarg** [comment]
I just tried making queues non-durable and it worked as expected yes.

**Comment by miguelgrinberg** [comment]
@xarg Awesome. Thank you so much!

**Comment by xarg** [comment]
Thanks for being responsive. I would like add some tests for this as well. I'm not familiar with Travis that much, but does it offer a RMQ server or something?

**Comment by miguelgrinberg** [comment]
The tests that I currently have on this repository are all unit tests, they do not have access to any real services, they mock the actual services to test that the code does the right thing. Travis does not provide anything to my knowledge, it would be a somewhat large effort to set up a system to run integration tests, at this point, and will likely incur in hosting costs for me, so I keep things limited to unit tests. If you would like to investigate mocking RabbitMQ to test this code, I would gladly accept that.

**Comment by xarg** [comment]
Got it. Do you think this one is included in the free plan? https://docs.travis-ci.com/user/database-setup/#RabbitMQ

If it's free, would you be open to integrations tests or still want to keep it simple with unittest mocking?

**Comment by miguelgrinberg** [comment]
Sure. I think there is quite a bit of work to set them up, but it would be good to have them, not only for RabbitMQ but for testing the package in general. Sounds like travis could provide enough infrastructure to get this done. You can create a new PR in which you edit the `.travis.yml` file to request those extra services, I think that's all you need to get the travis infrastructure in place.

**Comment by xarg** [comment]
Alright, I'm gonna do it.

**Comment by stuartspotlight** [comment]
Is this related to my issue with publisher disconnects? https://github.com/celery/kombu/issues/857

**Pull request merged**
