### PR TITLE
redis pub/sub support set password

### PR DESCRIPTION
**Pull request by larry-dev**
At first I added it to URL, but it was not easy to handle when the password value was None, so I added a parameter "password"

### CODE REVIEW

**Comment by miguelgrinberg** [comment]
I'm in the middle of a long trip back home today, I'll review this in a day or two. Thanks!

**Comment by larry-dev** [comment]
sorry,When do you plan to join this function?

**Comment by miguelgrinberg** [comment]
@larry-dev did you notice that the automated build is failing with your changes? Do you have time to fix those problems, or do you want me to? I can't merge this as is.

**Comment by larry-dev** [comment]
i fixed those problems.sorry,i didn't notice this error of build

**Comment by miguelgrinberg** [comment]
@larry-dev I modified your change to include the password in the URL, so that it is consistent with the non-async side. To add a password, use `redis://:password@hostname:6379/0`. Note that colon preceding the password, this is required per URL syntax.

**Pull request merged**
