### PR TITLE
Use a persistent ampq connection when publishing

### PR DESCRIPTION
**Pull request by sillyfrog**
The current `AsyncAioPikaManager` implementation creates a new connection for _every_ publish message, which is very expensive in the AMPQ protocol.

This addresses that, and (hopefully) the concerns raised in #692.

I'm not an advanced (nor intermediate) user of `asyncio`, so any feedback or advice is very welcome.

Thanks for the great library!

Fixes:  #691

### CODE REVIEW

**Comment by sillyfrog** [comment]
Some how I missed #935 - Closing

**Comment by sillyfrog** [comment]
Re-opening as I think this will be more robust vs #935 because of the lock around the connection creation

**Comment by miguelgrinberg** [comment]
Thanks. This wasn't as robust as I would have hoped, and also you've introduced some code duplication. I have now implemented this optimization along with some code cleanup and corresponding changes in the Kombu code. Please try out the main branch and let me know if there are any remaining issues.

**Comment by sillyfrog** [comment]
Testing the `async` build now, and it's looking good. Thanks!

That commit will also close #935 .

**Pull request closed without merging**
