### PR TITLE
fix : static not found

### PR DESCRIPTION
**Pull request by 625781186**
fix : static not found

### CODE REVIEW

**Comment by miguelgrinberg** [comment]
What version of django are you using. I see the import in the latest release: https://github.com/django/django/blob/master/django/core/management/commands/runserver.py#L23.

**Comment by 625781186** [comment]
> What version of django are you using. I see the import in the latest release: https://github.com/django/django/blob/master/django/core/management/commands/runserver.py#L23.

I use django==2.1.

this detail infos : https://github.com/miguelgrinberg/python-socketio/issues/347

**Comment by miguelgrinberg** [comment]
Does this work when using eventlet or gevent async modes?

**Comment by 625781186** [comment]
> Does this work when using eventlet or gevent async modes?

no , I haven't made any other changes to the example( [django_example/socketio_app/views.py](https://github.com/miguelgrinberg/python-socketio/blob/a839a36fa0fa7f0e5d8976ff47b217f6b1e8a44b/examples/server/wsgi/django_example/socketio_app/views.py) ).

**Comment by miguelgrinberg** [comment]
Tested latest version of Django and this problem does not exist anymore. Closing.

**Pull request closed without merging**
